### ISSUE TITLE
InternalOAuthError: failed to fetch user profile

### ISSUE THREAD

**Issue by JAertgeerts** [jaumard/trailpack-passport#105]
Setting up google oauth with the following package:
https://www.npmjs.com/package/passport-google-oauth2

My strategy config is as follows:
```
const GoogleStrategy = require('passport-google-oauth2').Strategy

...

google: {
      name: 'Google',
      protocol: 'oauth2',
      strategy: GoogleStrategy,
      options: {
        clientID: GOOGLE_CLIENT_ID,
        clientSecret: GOOGLE_CLIENT_SECRET,
        scope: ['profile'],
        callbackURL: GOOGLE_CALLBACK_URL,
        passReqToCallback: true
      }
    }
```

When successfully authenticating with Google, the correct callback url is called. For example:
http://localhost:3000/api/v1/auth/google/callback?code=CALLBACKCODE

However I'm getting the following error:
```
InternalOAuthError: failed to fetch user profile
    at /Users/jan/Documents/Code/app/node_modules/passport-google-oauth2/lib/oauth2.js:92:28
    at passBackControl (/Users/jan/Documents/Code/app/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/jan/Documents/Code/app/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickDomainCallback (node.js:429:17)
```

**Comment by jaumard** [comment]
Hum never test Google Auth2 but I think @LobeTia make it work with `passport-google-oauth`, did you try it ? Maybe he can help you. 
Check this https://github.com/jaumard/trailpack-passport/pull/104/files

**Comment by LobeTia** [comment]
I used both `passport-google-oauth` and `oauth2` and after some changes, I managed to make them work. 
Currently, I'm working on a PR for fix this issue, give me some days for write some tests and refine everything 😄

**Comment by JAertgeerts** [comment]
Just made it work. @LobeTia :
```
const GoogleStrategy = require('passport-google-oauth20').Strategy
...
google: {
      name: 'Google',
      protocol: 'oauth2',
      strategy: GoogleStrategy,
      options: {
        clientID: GOOGLE_CLIENT_ID,
        clientSecret: GOOGLE_CLIENT_SECRET,
        scope: ['https://www.googleapis.com/auth/userinfo.profile', 'https://www.googleapis.com/auth/userinfo.email'],
        callbackURL: GOOGLE_CALLBACK_URL,
        passReqToCallback: true
      }
    }
```

The scope was the one that was not working for me. Had to add in the entire URL instead of just 'profile'.

Important: 
add in Google+ API on https://console.developers.google.com/apis/
