### ISSUE TITLE
How to access profile fields oauth

### ISSUE THREAD

**Issue by JAertgeerts** [jaumard/trailpack-passport#106]
When defining the oauth strategy in apps not using this trailpack, one could use:
```
passport.use(new GoogleStrategy({
    clientID: GOOGLE_CLIENT_ID,
    clientSecret: GOOGLE_CLIENT_SECRET,
    callbackURL: "http://www.example.com/auth/google/callback"
  },
  function(accessToken, refreshToken, profile, cb) {
    User.findOrCreate({ googleId: profile.id }, function (err, user) {
      return cb(err, user);
    });
  }
));
```
And access the profile fields (such as gender, profile image and others).
How would you go about doing this using the trailpack?

**Comment by jaumard** [comment]
Here is the equivalent for this trailpack https://github.com/jaumard/trailpack-passport/blob/master/api/services/protocols/oauth2.js#L36 but it's done in background, you didn't have access to the profile, for now I just made the login capabilities and I mainly use local strategy. 

I have to think of a way to provide this functionality but don't know what's the best way to do it :/ if you have some ideas / feedback, it's welcome :)

**Comment by jaumard** [comment]
After a quick look I think we can inject a function (from the config.passport) here https://github.com/jaumard/trailpack-passport/blob/master/lib/passports.js#L88 with the user object and profile object and in return you send the user merged with the profile. What do you think ?

**Comment by JAertgeerts** [comment]
Ideally this would be a configuration per strategy. How can we get to the strategy config within passport.connect?

**Comment by jaumard** [comment]
I don't think you can because it's per protocole so you can only know if you are in oauth, oauth2, openid... I have to dig a little more to see if it's possible to retrieve the current strategy but look quite complicate

**Comment by JAertgeerts** [comment]
That's alright, most values are pretty much the same over the oauth2 providers and we can do things like:
```
// last_name is a facebook property, familyName is a google property
last_name: profile.name.last_name || profile.name.familyName
```
any way.

Only changes to get this working are:
passportsConfig.js
add in:
`  userProfile: joi.func(),`

In config/passport.js add a function
```
userProfile: (user, profile) => {
    return {
      email: user.email,
      gender: profile.gender,
      picture: profile.photos[0].value,
      last_name: profile.name.last_name || profile.name.familyName,
      first_name: profile.name.first_name || profile.name.givenName
    }
  }
```

in lib/passports.js change
`              app.services.FootprintService.create('user',user).then(user => {`
to
`              app.services.FootprintService.create('user', app.config.passport.userProfile(user, profile)).then(user => {`

I can open a PR with these changes, unless you want to make it a non breaking change and leave in the option to allow no function to be defined and just use 'user' object.

**Comment by jaumard** [comment]
To be consistent with onUserLogged it's better to return a Promise, like this if someone need async stuff they can (for example if they prefer download the avatar locally).
To don't have breaking change please add an empty function that return directly the user under config/passport.js 
Not sure about the name `userProfile` because it's too generic, maybe `mergeThirdPartyInfo` or `mergeThirdPartyProfile` what do you think ?
If you don't mind making the PR let do it :) please update the readme to add the new attribute and his capabilities.

Thanks !

**Comment by JAertgeerts** [comment]
Will do, thanks for the suggestions.

**Comment by JAertgeerts** [comment]
Looking at it now, I might want to add in the req param too. This to merge the other values on the request that might have been added.

What do you think?

**Comment by jaumard** [comment]
Do you have an example ? Because I can't see a usage for this as all third party redirects to an URL so params should be empty or everything the same values

**Comment by JAertgeerts** [comment]
Not applicable for 3rd party, no. I removed my comment.
For me, once the PR is merged - this can be closed.
