### ISSUE TITLE
Adding an option for disabling user login

### ISSUE THREAD

**Issue by LobeTia** [jaumard/trailpack-passport#112]
I'm working on a CMS where registration isn't allowed for everyone. Users must be pre-created by some kind of Admin.
I wanna work on a configuration for disabling the Register feature and allow Registration with a service that exposes some handlers for creating user and related passport instance

Does anyone have any better ideas about?

**Comment by jaumard** [comment]
To disable the registration you can just add a policy to intercept the registration and just return a forbidden (or whatever you want ^^), `PassportService.register` is what you looking for to create manually a User :) 

That answer your needs ?

**Comment by jaumard** [comment]
You can also use trailpack-acl to manage permission on registration / login per user / role

**Comment by LobeTia** [comment]
`PassportService.register` is the exact function I'm looking for
Using a Policy is a good way to achieve this, maybe adding a config just add more code to maintain and check.
Maybe we should document this

**Comment by jaumard** [comment]
Yeah if we can avoid adding code for stuff that can be manage by Trails it's better (less work like you said ^^). 
I didn't document this because for me it's "natural" to use policies but it can be a good idea to add this :)
