### ISSUE TITLE
Expanding user model

### ISSUE THREAD

**Issue by LobeTia** [jaumard/trailpack-passport#119]
I'd like to add some options for expanding the Sser model
My idea is to give the ability to reuse the existing User table for storing additional data without requiring a new model linked to User model

Somethings like

```
config/passport.js
{
   user:{
      schema:(app,Orm){
         firstName:{type: Orm.STRING},
         birthday: {type: Orm.DATE}
      },
      options: (app, Orm){
         getters:{
           getAge:(){ return ... }
         }
      }
   }
}
```
Maybe the trailpack should merge this additional configuration with user model checking for unnoticed key rewrite for the field used by the trailpack

Use cases:
- Adding additional data to users without required extra tables
- Expanding user functionalities without depending on this trailpack

I'm currently working on a cms where I must track name/surname, birthday, country and language for every user, for now I must use an additional table but I'd like to keep things clear

What do you think @jaumard ?

**Comment by jaumard** [comment]
The problem by doing that is it will be only on this trailpack that you can kind of extend the user model.
Currently when I need to extend the user model, I'm doing it like this (example taken from my L.I.S.A. project):

```
const _ = require('lodash')
const ModelPassport = require('trailpack-passport/api/models/User')
const ModelPermissions = require('trailpack-acl/api/models/User')

/**
 * @module User
 * @description User model
 */
module.exports = class User extends ModelPassport {

  static config(app, Sequelize) {
    return {
      options: {
        classMethods: {
          associate: (models) => {
            ModelPassport.config(app, Sequelize).options.classMethods.associate(models)
            ModelPermissions.config(app, Sequelize).options.classMethods.associate(models)

            models.User.hasMany(models.Dashboard, {
              as: 'dashboards',
              onDelete: 'CASCADE',
              foreignKey: {
                name: 'userId',
                allowNull: false
              }
            })
            models.User.belongsToMany(models.Device, {
              as: 'favorites',
              through: 'usersFavorites'
            })
            models.User.hasMany(models.Notification, {
              as: 'notifications',
              foreignKey: {
                name: 'userId'
              }
            })
          }
        }
      }
    }
  }

  static schema(app, Sequelize) {
    const userTrailpackSchema = ModelPassport.schema(app, Sequelize)
    const schema = {
      firstname: {
        type: Sequelize.STRING
      },
      lang: {
        type: Sequelize.STRING,
        defaultsTo: 'en'
      },
      lastname: {
        type: Sequelize.STRING
      },
      mobile: {
        type: Sequelize.STRING
      },
      avatar: {
        type: Sequelize.STRING
      }
    }

    return _.defaults(userTrailpackSchema, schema)
  }
}
``` 

By doing that way I can use multiple trailpack that have/need a User model and extend it like I want without specific notation/api

**Comment by LobeTia** [comment]
I like this approach
The only problem is that `_.defaults` is left to right and ignore new values for the same property.
You may fall into some compatibility errors without being noticed

But I think it's a good compromise, I will follow your approach ;)

**Comment by jaumard** [comment]
Yes, I use that because I know it's enough for now ^^ but you can use whatever you know to merge and build your model. But this way is more flexible than create stuff on this repo :)
