### ISSUE TITLE
3rd party connect to an existing user doesn't work

### ISSUE THREAD

**Issue by JAertgeerts** [jaumard/trailpack-passport#141]
UserId can't be null, association is created incorrectly.

**Comment by JAertgeerts** [comment]
In addition, connecting an existing account just logs that existing account in instead of throwing an error message (that it's the wrong user)

**Comment by JAertgeerts** [comment]
An approach could be to check if the req.user matches the passport.user when trying to update the passport token.

**Comment by jaumard** [comment]
Hum you're right I think we should do that check a return an error "Third party account already linked to another user" something like that... Can you add it to your PR ?

**Comment by JAertgeerts** [comment]
@jaumard Added to the PR

**Comment by JAertgeerts** [comment]
That doesn't seem right, need to rework it

**Comment by JAertgeerts** [comment]
Appears to be when using jwt (no session) the req.user is not populated. So the code works as expected and doesn't need a change. I'll revert the commit.
