### ISSUE TITLE
Password is a required field on passport model

### ISSUE THREAD

**Issue by ianvieira** [jaumard/trailpack-passport#168]
Why is the password a required field on the passport model? An user authenticating from a external provider will never receive a password from this provider, so, makes no sense the password be a required field if I'm creating a new user with Passport from a provide (like Spotify, for example). If the password needs to be required, at least a password should be generated before saving the model, as this generates a validation error on the model (what still not the perfect solution).

If you want, you can tell me the preferable approach to deal with this problem and I can create a PR for this.

**Comment by jaumard** [comment]
Witch ORM did you use ? After a quick look I think only mongoose require the password, it's a mistake as sequelize and waterline don't require it. 
If you want to create a PR please do :) 
Thanks

**Comment by ianvieira** [comment]
I use exactly Mongoose. I'll create a PR for this and also for a fix in the query, you cannot use findOne without the ID.

**Comment by jaumard** [comment]
Ok I never use/try mongoose, I use sequelize. Thanks for the PR ! :D I see also that protocol should be required and it's not. If you can put it on your PR it would be nice.

**Comment by ianvieira** [comment]
I created a PR that fixes the third-party auth in all the scenarios, I only tested it with Mongoose, but I believe we'll not have problems with the others ORMs.

**Comment by jaumard** [comment]
fix by https://github.com/jaumard/trailpack-passport/pull/169
