### ISSUE TITLE
Sequelize: Hooks should return Promises now. Callbacks are deprecated.

### ISSUE THREAD

**Issue by JAertgeerts** [jaumard/trailpack-passport#189]
http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html#breaking-changes

**Comment by jaumard** [comment]
If you have a crash it's more than deprecated then lol :D great doc ^^

**Comment by JAertgeerts** [comment]
@jaumard  can you publish a new version? that way I dont have to call to the repo anymore

**Comment by jaumard** [comment]
v2.1.6 ;)
