### ISSUE TITLE
Getting a JWT from local auth

### ISSUE THREAD

**Issue by ricick** [jaumard/trailpack-passport#198]
I'm struggling to figure out how with this library, to get the JWT from the local auth strategy, to be passed in with future JWT requests? Is there a way to make the login/register endpoints return a generated JWT instead of redirecting the user?

Thanks

**Comment by jaumard** [comment]
Hello, login and register endpoints return the user data and the JWT token.
Example: 
```
{
    "redirect": "/",
    "user": {
        "id": 1,
        "username": null,
        "email": "jimmy.aumard@gmail.com",
        "firstname": null,
        "lang": "fr",
        "lastname": null,
        "mobile": null,
        "avatar": null,
        "createdAt": "2017-06-22T17:50:36.152Z",
        "updatedAt": "2017-06-22T17:50:36.152Z"
    },
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6bnVsbCwiZW1haWwiOiJqaW1teS5hdW1hcmRAZ21haWwuY29tIiwiZmlyc3RuYW1lIjpudWxsLCJsYW5nIjoiZnIiLCJsYXN0bmFtZSI6bnVsbCwibW9iaWxlIjpudWxsLCJhdmF0YXIiOm51bGwsImNyZWF0ZWRBdCI6IjIwMTctMDYtMjJUMTc6NTA6MzYuMTUyWiIsInVwZGF0ZWRBdCI6IjIwMTctMDYtMjJUMTc6NTA6MzYuMTUyWiJ9LCJpYXQiOjE1MTA1MTE0OTksImV4cCI6MTUxMDU5Nzg5OSwiYXVkIjoibG9jYWxob3N0IiwiaXNzIjoibG9jYWxob3N0In0.Uf78JfPYgAQOKh4RqveilLLP9C9VEWAyDyQ2UNfQacA"
}
```

The only thing that you can customize is the user data returned by putting onUserLogged callback on your passport.js configuration file like this https://github.com/jaumard/trailpack-passport/blob/master/config/passport.js#L9

**Comment by ricick** [comment]
I found my issue. I wasn't passing the accept:application/json header in postman.

**Comment by jaumard** [comment]
Glad you found it ! 👍 :)
