### ISSUE TITLE
Better error management

### ISSUE THREAD

**Issue by jaumard** [jaumard/trailpack-passport#39]
Actually if ORM return an error, a 500 is throw instead of a 400. Check all error message to return a good one

**Comment by JAertgeerts** [comment]
For 3rd party login: Sequelize constraint errors are a pain too if they're unhandled as they just show up as plain text in the callback endpoint

**Comment by jaumard** [comment]
Hi @JAertgeerts ! I never try third party login :( so yes it may have some trouble with that sorry, can you make a PR with the fix ? Like this I can take a look and see the differences with the existing code as I don't have a lot of time for now it will help.
Thanks!
