### ISSUE TITLE
request-feature(stateless-auth): Logout should require jwt when logout and not use the session.

### ISSUE THREAD

**Issue by maissani** [jaumard/trailpack-passport#40]
# Feature Request
### Intro

Hi, 
The logout statement of trailpack-passport is not yet fully stateless, 
when using jwt, it will be better to have to prodive a json web token in order to get logout. 
This can be an optional parametter like the example: 

### Example

``` JavaScript
# config/session.js
stateless : true # false should use the session
````

Cordialy, 
Mehdi AISSANI

**Comment by jaumard** [comment]
If you want to force JWT token for logout  just add the policy for it like `config/policies.js` : 

```
...
 AuthController: {
   logout: [ 'PassportPolicy.jwt' ]
 }
...
```

**Comment by maissani** [comment]
Off course, 
But behind the veil it's remains a session so not fully stateless because of session treatment.

If people doesn't mather with the only fact that passing a jwt resolve the statless issue, you can consider that it's resolved by just adding an example. 

It's appear to be Resolved for me because i doesn't mather about that for the moment.

Cordialy,

**Comment by jaumard** [comment]
To remove the session just remove `config.session.secret` field and also the `session` and `passportSession` middleware of express at `config.web.middlewares.order` and you will have no session anymore :) it doesn't depends of this trailpack. It's just depends how you configure express.
