### ISSUE TITLE
major-change(auth-response): use of 401 instead of 403 when user is not authenticated and try access a restricted ressouce

### ISSUE THREAD

**Issue by maissani** [jaumard/trailpack-passport#41]
# Major Change Request

## Description

Trailpack-passport currrently return a 403 when user is not authenticated, it should be 401(user not authenticated error) error code because 403 is an access deny ( can be confuse with a policy reject ).

Cordialy, 
Mehdi AISSANI

**Comment by jaumard** [comment]
Fix on https://github.com/jaumard/trailpack-passport/commit/9e98ad16b9051c2785d3a5fcb15c676028e01d64

**Comment by maissani** [comment]
Nice :) , 
👍

**Comment by jaumard** [comment]
Deploy on v1.0.0-beta-7
