### ISSUE TITLE
Trailpack doesn't get added to main.js when using yo. 

### ISSUE THREAD

**Issue by Fahrradflucht** [jaumard/trailpack-passport#43]
I'm not a 100% sure that this is not intended behavior, but I spent about 2hours figuring out why my app doesn't work like the example until I realized that the yo generator didn't add the trailpack to main.js.

So I think it should either be changed to do that or be documented in the "using yo" section.

**Comment by jaumard** [comment]
Sorry about that.
I just added this to the Readme on configuration part. Hope soon the generator will add it automatically.
Thanks for the report !
