### ISSUE TITLE
Error in bcypt encryption

### ISSUE THREAD

**Issue by ycpatel813** [jaumard/trailpack-passport#45]
hi 
I am using window 7 OS.
When i am installing trailpack-passport i found error.
```javascript
D:\trails-example-express-master>yo trails:trailpack trailpack-passport
D:\trails-example-express-master\node_modules\trailpack-passport\node_modules\bc
rypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
  else (node "" rebuild )
1
```

I searched over and i found there is bcrypt error in windows OS.
I need to install python as well as Visual studio to solve out this error(May be)
but if trails passport provide config or someing facility to change encryption method it is good for windows user also.

**Comment by jaumard** [comment]
Yeah bcrypt is quite complicate to make it work on windows (but it's possible ^^).

> but if trails passport provide config or someing facility to change encryption method it is good for windows user also.

That will not be enough, trails passport also have to don't include any encryption method at all (or not bcrypt) because install will fail on windows anyway if bcrypt is under packages

**Comment by ycpatel813** [comment]
i made hack and working fine with me in window now.thanks and you can close this issue.

**Comment by jaumard** [comment]
Great ! :) don't hesitate to share it maybe other windows users will need it ^^

**Comment by TareqElMasri** [comment]
Use node-bcrypt package instead of c++ bcrypt. bcrypt causes a lot of compiling issues with a lot of machines. node-bcrypt uses native javascript with the same methods
