### ISSUE TITLE
Send expiration time with issued tokens.

### ISSUE THREAD

**Issue by Fahrradflucht** [jaumard/trailpack-passport#46]
Atm there is no way for a client to no how long the issued JWT is valid (correct me if I'm wrong).
I'm new to JWTs but this seems quite unpractical to me since the client now either has to _know_ the EXPIRES_IN_SECONDS constant or needs to make a request which returns ___*

\* At this point I wanted to put in the error I expected to get if the token is expired but I wasn't able to find the corresponding code...

**Comment by jaumard** [comment]
Hum in fact I never make a real project with JWT so I'm new too but I never see the time constant return with the token, why to you need it ? Because when the token is expired you'll get a 401 with an error message.

**Comment by Fahrradflucht** [comment]
Hm I don't find an example either, but I thought for some reason that it this is common...

I just think that this is leads to a lot of unnecessary requesst for the client if there is no way to know, that the token is expired. For good UX you then get into the habit of checking if your token is still valid every time at points where a login dialog fits better in just to not get a 401 when you really want to make the request.

--

Ah xD I just thought of an example where someone talked about getting the expire date with the token:
@tjwebb over at YT -> https://youtu.be/P1dZfPUynTo?t=41m38s

**Comment by jaumard** [comment]
Hum ok ^^ never use expire date but why not :) I use the token until I get a 401 then ask the user to log again ^^

**Comment by wyemun** [comment]
The reason of token expiry is so that the client will know when to request for new token (provided they got a refresh token in the first place)

Are you planning to add the Refresh token as well?

[https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/](Auth0 Refresh Token)

**Comment by jaumard** [comment]
I don't have time to add those things :( but I would be happy to accept and merge a pull request about this if you want to do it. Like I say I use status code 401 to trigger a refresh token. Never use auth 0 before but yeah refresh token must be return in this case

**Comment by jaumard** [comment]
I did a little into tokens and stuff and the expiration date is already under the token. Just parse the token and you'll have it. So the client can detect if token is expired. I just did it in my Android application. 

Here is the code I use (it's in Java but it will be the same in JS, or you can use an existant module that parse token.) : 

```
User user = null;
        String[] parts = token.split("\\.");
        if (parts.length == 3) {
            Gson gson = new Gson();
            Token response = gson.fromJson(new String(Base64.decode(parts[1].getBytes(), 0)), Token.class);
            user = response.getUser();
        }
```

My token class is : 
```
public class Token {
    private long iat;
    private long exp;
    private String iss;
    private String aud;
    private User user;
...
}
```
The exp attributs contains the expiration date in seconds.
