### ISSUE TITLE
Passports data returned when connect

### ISSUE THREAD

**Issue by Skalv** [jaumard/trailpack-passport#55]
Hi !

Not really a question, but more a reflexion.
When I connect to `/auth/local/connect`, the default response is : 

``` json
{
"redirect":"/",
"user":{
  "id":1,
  "username":"Skalv",
  "email":"tutu@titi.com",
  "createdAt":"2016-06-27T14:22:03.000Z",
  "updatedAt":"2016-06-27T14:22:03.000Z",
  "passports":[{
    "id":1,
    "protocol":"local",
    "password":"$2a$10$Y0y2syuiHnGKoni8k4v61uzrRV92ThyYKLrw6jnLFVG/o4ufQN8.y",
    "provider":null,
    "identifier":null,
    "tokens":null,
    "createdAt":"2016-06-27T14:22:03.000Z",
    "updatedAt":"2016-06-27T14:22:03.000Z",
    "UserId":1
   }]
},
"token": "tututititoto"
}
```

In, there is passports data and mainly the encrypted password, this is not a security vulnerability ?

**Comment by jaumard** [comment]
Hi ! 

To be honest I don't... That's why I give the possibility to remove it if you want by using the `onUserLogged` callback, my modify what you want on the User object and that's what is returned later. But yeah maybe it will be better if I remove it by default...

**Comment by jaumard** [comment]
I just fix this, by default `passports` is not return anymore, but if you override `onUserLogged` you'll have to remove it yourself because you override the default behavior
