### ISSUE TITLE
Support for trailpack-mongoose

### ISSUE THREAD

**Issue by Nishchit14** [jaumard/trailpack-passport#77]
This Trailpack work only with trailpack-sequelize or trailpack-waterline as ORM

It would be fine if we add support for [trailpack-mongoose](https://github.com/trailsjs/trailpack-mongoose)

**Comment by jaumard** [comment]
As I see now trailpack-mongoose is now compatible with footprints associations (it was not the case before). So in order to support this ORM, Passport and User model need a mongoose definition, then tests need to change to run with trailpack-mongoose and see if all is ok :)
Nothing too complicated, but I didn't know mongoose so if anyone want to do a PR with the model definitions it will help me because it will take me more time than someone who know mongoose.

**Comment by Nishchit14** [comment]
Ok!! I'll see, If I can help you.

**Comment by LobeTia** [comment]
I can work about it, in past I used mongoose in a lot of projects
Maybe instead of a wall of if I can implement some kind of strategy pattern for loading the correct schema for that ORM

Somethings like
```
module.exports = class User extends Model {
   static config(app){
      return SchemaUtil.GetConfig("User", app.config.database.orm)
   }
   static schema(app, Sequelize){
      return SchemaUtil.GetSchema("User", app.config.database.orm)
   }
}
```

**Comment by jaumard** [comment]
I think it's a good idea to have a clear models classes and yeah it start to be quite big ^^ 
I think it will be better to export config/schema into a file per ORM and just do switch / if else into methods to require the good one.

Somethings like : 

```
//sequelize.js
module.exports = {
  config: (app, Sequelize) => { return stuff },
  schema: (app, Sequelize) => { return stuff }
}

//User.js
module.exports = class User extends Model {
   static config(app, Sequelize){
      if (app && app.config.database.orm === 'sequelize') {
         return require('./sequelize').config(app, Sequelize)
      }
      ....
   }
   static schema(app, Sequelize){
      if (app && app.config.database.orm === 'sequelize') {
         return require('./sequelize').schema(app, Sequelize)
      }
   }
}
``` 
Quick code but something like this would be nice. 

The problem with the strategy pattern is `"User", app.config.database.orm` is not enough to create a config or schema for some ORM, for example sequelize need his instance, if you want to add some hook you will need trails instance too to access services and stuff... Or it have to be more like `SchemaUtil.getSchema("User", app) ` that can work too but don't like much the fact you pass "User" when it can be avoided. 

What do you think ?

**Comment by jaumard** [comment]
@LobeTia @Nishchit14 
I just update the ORM definition to make it cleaner :) now it need model definitions for mongoose

**Comment by LobeTia** [comment]
I see, excellent work! I'm gonna work on a first integration this weekend
Keep you updated
